[[redirects]]
  from = "/img/logo-medium.jpg"
  to = "/.netlify/images/?url=/img/logo.jpg&q=100&fit=contain&w=130"
  status = 200

[[redirects]]
  from = "/img/20250520_135728.jpg"
  to = "/.netlify/images/?url=/img/20250520_135728.jpg&q=85&fit=contain&w=552"
  status = 200

[[redirects]]
  from = "/img/logo-small.jpg"
  to = "/.netlify/images/?url=/img/logo.jpg&q=100&fit=contain&w=100"
  status = 200
